### ISSUE TITLE
i think you make a big mistake,imgt cdr annotation is not supported

### ISSUE THREAD

**Issue by qiuqingpo** [xinyu-dev/annotate_v#3]
I see the webapi interface detail, the type of the imgt is not supported, there is no imgt options
http://www.bioinf.org.uk/abs/abnum/

**Comment by xinyu-dev** [comment]
Thanks for brining it to my attention. You're correct that IMGT option has been removed.

**Comment by qiuqingpo** [comment]
> Thanks for brining it to my attention. You're correct that IMGT option has been removed.
do you have any other solutions for it? thank you！

**Comment by xinyu-dev** [comment]
As mentioned before you can try anarci
